### ISSUE TITLE
containers/loginForm/modules.js

### ISSUE THREAD

**Issue by jurij** [Andreas19810601/newManager#6]
`setUserLogin`:
- so wenig wie nötig an actions dispatchen
- pattern nutzen
  - vor dem axios request `SET_USER_LOGIN_REQUESTED` dispatchen 
  - nach dem request `SET_USER_LOGIN` dispatchen
  - mit `SET_USER_LOGIN` können diese zusammengefasst werden
    - dispatch(setUserRole(res.data.user.role))
    - dispatch(setUserName(p.identifier))
    - dispatch(setUserDisplayName(res.data.user.displayName))
    - dispatch(setUserPassword(p.password))

**Comment by Andreas19810601** [comment]
done
